### ISSUE TITLE
[Feature]: consolidate deployment scripts

### ISSUE THREAD

**Issue by wincowgerDEV** [code4sac/trash-ai#106]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Reviewer 1 says: Even with the current structure, I'll also note that the deployment scripts and such could probably be simplified and consolidated a bit - when taking a brief look at it, it felt like I had to jump around a bit to find all the different bits and pieces and had a lot of different calls between different tools (eg, why use makefiles vs just having a single docker-compose in the root and use docker-compose up?).

### Problem

Challenging deployment

### Proposed Solution

Make deployment scripts easier to follow. 

### Alternatives Considered

NA

**Comment by shollingsworth** [comment]
Minus the aws/github stuff can this be closed with #127 and #107 ?

**Comment by wincowgerDEV** [comment]
You're a legend @shollingsworth! Yeah, I think this is settled, closing now.
