### ISSUE TITLE
[Feature]: Need to be more explicit about data sharing

### ISSUE THREAD

**Issue by wincowgerDEV** [code4sac/trash-ai#122]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Reviewer said: While it is stated in the paper that some of the images are uploaded to an S3 storage there is no information about it on your trashai.org webpage. I think it is at least necessary to put a disclaimer to users that their image data is uploaded and that images may contain delicate information through exif data (because I think the targeted audience is not always aware of what information images may contain). In my view it would even be better to have an opt-out option for image upload and/or stripping unnecessary parts of the exif data while uploading and/or informing users of uploading process to aws while also putting information resources to exif data directly on the page.

### Problem

Not clear enough information about what happens to data when it goes to the website. Users don't have a way to opt out of data sharing. 

### Proposed Solution

Add popup or info box near the data upload that tells the user where their data will be shared and allows them or opt out. 

### Alternatives Considered

Expect users to read the documentation.

**Comment by shollingsworth** [comment]
We might want to update the current paper to say we're not actually doing any interaction with the backend as of now. In its current state it's only a web frontend. In the future we may implement this, but it's not a factor at the moment.

**Comment by wincowgerDEV** [comment]
Good call! I am on it.

**Comment by wincowgerDEV** [comment]
Updated the paper 2527ec10682118e6ba60a4dba2026e0460e82b73, now put this as a future task since it wasn't implemented.
