### ISSUE TITLE
Drag and Drop the same image  multiple times generates Vue Duplicate Key warning

### ISSUE THREAD

**Issue by zfi** [code4sac/trash-ai#25]
The duplicate key warning is triggered in the console when draging and dropping the same image file in two or more separate drag-drop operations. 

The attached log file contains the full stack trace.

```
vue.runtime.esm.js:619 [Vue warn]: Duplicate keys detected: 'Screen Shot 2022-02-07 at 10.38.15 AM.png'. This may cause an update error.

found in

---> <TestUpload> at src/components/test/upload.vue
       <VCard>
         <Src/pages/index.vue> at src/pages/index.vue
           <Nuxt>
             <VMain>
               <VApp>
                 <NavBase> at src/components/nav/base.vue
                   <Default> at src/layouts/innertab.vue
                     <Root>
```
[localhost-1647059099920.log](https://github.com/code4sac/trash-ai/files/8237073/localhost-1647059099920.log)

**Comment by shollingsworth** [comment]
HRM, should be easy enough to fix. I think the drop zone component has a duplicate file event we can use as well.

**Comment by shollingsworth** [comment]
Fixed.
