### ISSUE TITLE
[BUG] Non-www trashai.org does not resolve

### ISSUE THREAD

**Issue by feydan** [code4sac/trash-ai#47]
Visting https://trashai.org/ does not resolve -- you have to hit the www version https://www.trashai.org/.

We should either redirect non-www to www OR host the app at non-www and redirect www to it.

**Comment by shollingsworth** [comment]
That's right, we need to insert an alias.

**Comment by shollingsworth** [comment]
The instance I'm hosting in my personal account is working with the root domain.
 I think we might have to tear down the frontend stack, and re-run the setup because some of the changes to infra aren't taking place/ being enforced.
