### ISSUE TITLE
Add google analytics tracking

### ISSUE THREAD

**Issue by feydan** [code4sac/trash-ai#53]
We want to track how many people use TrashAI.

**Comment by KristiinaKerge** [comment]
Have you considered alternative service for analytics? the data ownership and privacy is questionable in Google
here is one overview https://kinsta.com/blog/google-analytics-alternatives/

**Comment by feydan** [comment]
We did not consider alternatives.  That being said, our analytics needs are not super complex at the moment, and I would be open to alternatives if you or someone else wants to help work on implementing that.
