### ISSUE TITLE
Need beginner installation instructions for Local Deployment

### ISSUE THREAD

**Issue by wincowgerDEV** [code4sac/trash-ai#71]
The journal submission requires that we make sure there are pretty detailed deployment instructions for someone who is at least familiar with the coding language we are using. I think they will only review the local deployment as AWS deployment is a little outside the scope of the journal. Could we go through the local deployment https://github.com/code4sac/trash-ai/blob/production/docs/localdev.md and make sure that someone starting from having nothing downloaded on their device could get this up and running there? Maybe this already has been done, if so let me know!

**Comment by shollingsworth** [comment]
https://github.com/code4sac/trash-ai/blob/production/docs/localdev.md
^ this is the current instructions for local dev, and what we'll need to iterate on.

**Comment by shollingsworth** [comment]
closing this in leu of #85
