### ISSUE TITLE
Add a tool to annotate images

### ISSUE THREAD

**Issue by feydan** [code4sac/trash-ai#74]
We'd like to improve the model over time.  

One way we can do that is to have a way to look at images that have no annotations and be able to draw and label trash in the images in the browser.  We could also have a way to modify existing bounding boxes and label.

Ideally we would also upload the image and the new annotations to an s3 bucket so that we can use that data for future model refinement, but this can be addressed in a future issue to reduce scope of this one. (if not addressed in this ticket, open a new one when this is closed)

**Comment by HiGregory** [comment]
Noted. @feydan Did a fork and working on a path to this.

Ideally hoping annotation could also be supported by designated groups (e.g Residents, Assigned annontators)

**Comment by shollingsworth** [comment]
@HiGregory
branch https://github.com/code4sac/trash-ai/tree/classification_addition already has a lot of the work done for this fwiw.
You can switch the branch and run the local dev instance to see what that looks like. Improvements are welcome.

**Comment by shollingsworth** [comment]
This has been implemented but disabled until we can get machine learning piece in place.
