### ISSUE TITLE
Review Manuscript 

### ISSUE THREAD

**Issue by hernandezforges** [code4sac/trash-ai#75]
@wincowgerDEV would like to have the manuscript reviewed by 11/15/2022. If you have been assigned, please comment after you have reviewed the manuscript.

**Comment by maryfnorris** [comment]
I will take a look . Appreciated!

**Comment by shollingsworth** [comment]
@wincowgerDEV can you confirm we can close this?

**Comment by wincowgerDEV** [comment]
Yeah, this is done thanks!
