### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by wincowgerDEV** [code4sac/trash-ai#80]
@createHernandez recommended we add issue templates, love the idea! saw this on another repo recently and was really impressed by the experience and also the data they got in the end from the issue was much higher quality. 

I initially signed up for this but I don't have access to change the settings and would need access to be able to get this going. I ended up deploying it on another [repo](https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal) in just about 5 min using these [instructions](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) and mostly the vanilla settings. If someone wants to give me settings access I would be happy to set it up, just let me know.

**Comment by wincowgerDEV** [comment]
This is actually a really good example of how you can do it for a whole organization which may be the way to go for code for sac as an organization. Basically just create a .github/ISSUE_TEMPLATE folder and add these yaml files to it. 

https://github.com/Appsilon/.github/tree/main/.github/ISSUE_TEMPLATE

**Comment by wincowgerDEV** [comment]
Nevermind, I figured out a way to add it to the manuscripts PR #69

**Comment by epierotti3** [comment]
I'm picking this back up because it's a great idea. We currently have templates for bug reports and feature requests. I'd like add a blank template that can be used by pretty much anyone in any role. Something like:
```

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX/BE ON HOLD

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.
- [ ] Task 1
- [ ] Task 2...

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.


```

Would love feedback - would this be useful? Is is structured enough to provide the assignee enough information to work on it, but flexible enough that it could be used in a variety of roles/contexts?
