### ISSUE TITLE
Testing Local Deployment Issues

### ISSUE THREAD

**Issue by wincowgerDEV** [code4sac/trash-ai#85]
This comes from our coauthor Kris Haamer who tested out the local deployment on his mac and was able to get it to run but had a few challenges. 
<img width="1920" alt="detections" src="https://user-images.githubusercontent.com/26821843/197840754-b04ec654-dd98-409a-9f95-cf5031d23fad.png">

1. The local branch mentioned in the docs doesn't exist (I used the production branch) - or I guess the docs mean to say: create your own local branch
2. Maybe mention the need for a Google Maps API key in the docs (the compiler complains VITE_GOOGLE_MAPS_API_KEY is missing) - AWS Amplify seems to require it but not sure where and for what it's going to be used

**Comment by shollingsworth** [comment]
I'll take a look at this @wincowgerDEV thanks.

**Comment by wincowgerDEV** [comment]
Thanks 🙏

**Comment by shollingsworth** [comment]
@wincowgerDEV can you have your friend Re-test to confirm the docs and build work correctly?

**Comment by wincowgerDEV** [comment]
Thanks Steven! I'll reach out to them.

**Comment by wincowgerDEV** [comment]
Haven't heard back from my friend so was trying to dive into this myself but then realized that we haven't incorporated his previous comments yet: https://github.com/code4sac/trash-ai/issues/85#issue-1422815405 Will make a PR for them now.

**Comment by shollingsworth** [comment]
> Haven't heard back from my friend so was trying to dive into this myself but then realized that we haven't incorporated his previous comments yet: [#85 (comment)](https://github.com/code4sac/trash-ai/issues/85#issue-1422815405) Will make a PR for them now.

If you look at the diff, I think I did, unless I missed something.

**Comment by wincowgerDEV** [comment]
Will take a look deeper, I was looking for commits to the local deployment
md file.

**Comment by wincowgerDEV** [comment]
> If you look at the diff, I think I did, unless I missed something.
This one says the last update was March, maybe there are some commits that haven't been pushed? https://github.com/code4sac/trash-ai/blob/production/docs/localdev.md

I am starting to work on this in the Manuscript branch now so no worries about it either way.

**Comment by shollingsworth** [comment]
@wincowgerDEV  

This is part of a PR related to this issue, probably should have linked it in the first place :-P
https://github.com/code4sac/trash-ai/compare/85-testing-local-deployment-issues
^^^

**Comment by wincowgerDEV** [comment]
Right on, I made a PR for it and will add some updates there. Thanks :) https://github.com/code4sac/trash-ai/pull/86

**Comment by wincowgerDEV** [comment]
Currently running for Windows, this statment is unclear to me "WSL Integration on Ubuntu must be enabled in Docker options -> Resources -> WSL Integration" Is that something I would do through the Linux command prompt? It looks like  docker desktop already has the integration by default so maybe we just recommend they install that? 
![image](https://user-images.githubusercontent.com/26821843/202787531-9e8c644c-ee49-4e5e-a374-a3b835f05ebf.png)

**Comment by wincowgerDEV** [comment]
Are we sure these instructions are necessary? I think that docker-compose is now coming standard with any docker desktop installation.

See here: https://docs.docker.com/compose/install/

"docker-compose [Instructions](https://docs.docker.com/compose/install/)
Docker-compose file version >3.7 are supported
Windows: Take note of docker-compose installation (installing through apt may not install the correct version)
For MacOS, use docker-compose version 1.x"

**Comment by shollingsworth** [comment]
> Are we sure these instructions are necessary? I think that docker-compose is now coming standard with any docker desktop installation.
> 
> See here: https://docs.docker.com/compose/install/
> 
> "docker-compose [Instructions](https://docs.docker.com/compose/install/) Docker-compose file version >3.7 are supported Windows: Take note of docker-compose installation (installing through apt may not install the correct version) For MacOS, use docker-compose version 1.x"

Some folks may not be using docker desktop. Maybe just recommend docker desktop, and we can remove that part.

**Comment by shollingsworth** [comment]
> Currently running for Windows, this statment is unclear to me "WSL Integration on Ubuntu must be enabled in Docker options -> Resources -> WSL Integration" Is that something I would do through the Linux command prompt? It looks like docker desktop already has the integration by default so maybe we just recommend they install that? ![image](https://user-images.githubusercontent.com/26821843/202787531-9e8c644c-ee49-4e5e-a374-a3b835f05ebf.png)

I think @feydan  put the windows instructions together. If you're following along on Windows, I say modify it to make sense to you going through the process new.

**Comment by wincowgerDEV** [comment]
Thanks! Doing that now :)

Getting pretty close to the full deployment, currently at the make local step and got this error. Do we need to require that people login to docker? Also tried logging in but still get the same error message. 

"Error response from daemon: pull access denied for trash_ai_bs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make[1]: *** [Makefile:5: up] Error 18
make[1]: Leaving directory '/home/wincowger/code/trash-ai/localdev'
make: *** [Makefile:2: local] Error 2"

**Comment by wincowgerDEV** [comment]
> > Are we sure these instructions are necessary? I think that docker-compose is now coming standard with any docker desktop installation.
> > See here: https://docs.docker.com/compose/install/
> > "docker-compose [Instructions](https://docs.docker.com/compose/install/) Docker-compose file version >3.7 are supported Windows: Take note of docker-compose installation (installing through apt may not install the correct version) For MacOS, use docker-compose version 1.x"
> 
> Some folks may not be using docker desktop. Maybe just recommend docker desktop, and we can remove that part.

Agreed, probably simpler for us to document.

**Comment by shollingsworth** [comment]
> Thanks! Doing that now :)
> 
> Getting pretty close to the full deployment, currently at the make local step and got this error. Do we need to require that people login to docker? Also tried logging in but still get the same error message.
> 
> "Error response from daemon: pull access denied for trash_ai_bs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied make[1]: *** [Makefile:5: up] Error 18 make[1]: Leaving directory '/home/wincowger/code/trash-ai/localdev' make: *** [Makefile:2: local] Error 2"

No, it actually should be building `trash_ai_bs`, so it doesn't have to reach out for that local image.
I'm on slack if you want to go over that realtime.

**Comment by wincowgerDEV** [comment]
> No, it actually should be building `trash_ai_bs`, so it doesn't have to reach out for that local image. I'm on slack if you want to go over that realtime.

Sweet thanks! Logging onto slack.

**Comment by wincowgerDEV** [comment]
Thanks @shollingsworth for debugging the error with me. Was able to get a successful deployment and went through the rest of the instructions and made sure they are ready to roll. Local deployment instructions are good to go to me.
